version: '2.1'

networks:
  rim:
    driver: bridge

services:
   # login med {testbruger1,testbruger2}/Test1234 
   medarbejder-login-proxy:
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
      command: --config /oauth2-proxy.cfg
      ports:
       - 4180:4180
      volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
      networks:
       - rim

   medarbejder-bff:
      image: kvalitetsit/hjemmebehandling-medarbejder-bff:4b7b527c1ff754d4e0a19acde2dda2d2c06e2eb1
      environment:
       - cpr.url=http://rm-cpr-service:8080/Patient/
      networks:
       - rim
       
   medarbejder-web:
     image: kvalitetsit/hjemmebehandling-medarbejder-web:f5b87f7fda54f2a2e39a669982cd5c1f1a96b853
     ports:
      - 3000:3000
     environment:
      - BFF_BASE_URL=http://medarbejder-bff:8080
     networks:
      - rim

   # Mulige patienter kan ses i DIAS git. Patienter fremsøges via GET, f.eks. http://localhost:8081/Patient/2512489996
   rm-cpr-service:
     image: kvalitetsit/rm-cpr-service:0.2.0
     environment:
      - CPR_ENDPOINT=http://rm-cpr-service-mock:8080
      - DEBUG_LOGGING=true
     networks:
      - rim
     ports:
      - "8081:8080"

   rm-cpr-service-mock:
     image: kvalitetsit/rm-cpr-service-mock-backend:0.2.0
     environment:
      - DEBUG_LOGGING=true
     networks:
      - rim
     
   hapi-server:
     image: hapiproject/hapi:latest
     networks:
      - rim
     environment:
       - SPRING_CONFIG_LOCATION=file:///data/hapi/application.yaml
       - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
     volumes:
       - ./hapi-server/application.yaml:/data/hapi/application.yaml
 
   hapi-server-initializer:
     image: alpine:3.11.5
     depends_on:
       - hapi-server
     networks:
      - rim
     volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
     command: "/hapi-server-initializer/init.sh"
