version: '3.9'

networks:
  hjemmebehandling:
    driver: bridge

services:
    
   medarbejder-bff:
    image: kvalitetsit/hjemmebehandling-medarbejder-bff:dev
    environment:
      - userattributes_role_key=DIAS_HJEMMEBEHANDLING_Sygeplejerske2
      # - userattributes_org_key=organization-infektionsmedicinsk
      - user.context.handler=MOCK
      - user.mock.context.organization.id=453071000016001
      - cpr.url=http://rm-cpr-service:8080/Patient/
      - fhir.server.url=http://hapi-server:8080/fhir
      - allowed_origins=http://localhost:3000
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - allowed.roles=DIAS_KoMo_Laege,DIAS_KoMo_Sygeplejerske,DIAS_KoMo_Administrator, Administrator, DIAS_HJEMMEBEHANDLING_Sygeplejerske2
      - allowed.admin.roles=Administrator,DIAS_KoMo_Administrator, Administrator, DIAS_HJEMMEBEHANDLING_Sygeplejerske2
    ports:
      - 8090:8080
      - 5005:5005
    networks:
      - hjemmebehandling

   patient-bff:
    image: kvalitetsit/hjemmebehandling-patient-bff:dev
    environment:
      - user.mock.context.cpr=0104909995
      - cpr.url=http://rm-cpr-service:8080/Patient/
      - fhir.server.url=http://hapi-server:8080/fhir
      - user.context.handler=MOCK
      - allowed_origins=*
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - allowed.roles=DIAS_KoMo_Laege,DIAS_KoMo_Sygeplejerske,DIAS_KoMo_Administrator, DIAS_HJEMMEBEHANDLING_Sygeplejerske2
      - allowed.admin.roles=Administrator,DIAS_KoMo_Administrator 
    ports:
      - 8091:8080
      - 5006:5005
    networks:
      - hjemmebehandling

   patient-web-init:
    image: kvalitetsit/hjemmebehandling-patient-web:dev
    restart: always
    environment:
      - REACT_APP_BFF_BASE_URL=http://patient-bff:8080
      - REACT_APP_NODE_ENV=dev
      - REACT_APP_KEYCLOAK_URL=https://keycloak.sdn.t0.hosting.kitkube.dk/auth
      - REACT_APP_KEYCLOAK_REALM=aftaleportal-test
      - REACT_APP_KEYCLOAK_CLIENTID=aftaleportal-ui
    networks:
      - hjemmebehandling
    volumes:
      - ./patient-web/init/docker-entrypoint.d:/temp/docker-entrypoint.d
      - ./patient-web/init/etc/nginx:/temp/etc/nginx
      - ./patient-web/init/var/run:/temp/var/run
      - ./patient-web/init/var/cache/nginx:/temp/var/cache/nginx

   patient-web:
    image: nginxinc/nginx-unprivileged:alpine3.17
    restart: always
    volumes:
      - ./patient-web/init/docker-entrypoint.d:/docker-entrypoint.d
      - ./patient-web/init/etc/nginx:/etc/nginx
      - ./patient-web/init/var/run:/var/run
      - ./patient-web/init/var/cache/nginx:/var/cache/nginx
    ports:
      - "3001:80"
    depends_on:
      - patient-web-init
    networks:
      - hjemmebehandling

   medarbejder-web-init:
    image: kvalitetsit/hjemmebehandling-medarbejder-web:dev
    environment:
      - REACT_APP_BFF_BASE_URL=http://medarbejder-bff:8080
      - REACT_APP_NODE_ENV=dev
      - REACT_APP_KEYCLOAK_URL=https://keycloak.sdn.t0.hosting.kitkube.dk/auth
      - REACT_APP_KEYCLOAK_REALM=aftaleportal-test
      - REACT_APP_KEYCLOAK_CLIENTID=aftaleportal-ui

    volumes:
      - ./medarbejder-web/init/docker-entrypoint.d:/temp/docker-entrypoint.d
      - ./medarbejder-web/init/etc/nginx:/temp/etc/nginx
      - ./medarbejder-web/init/var/run:/temp/var/run
      - ./medarbejder-web/init/var/cache/nginx:/temp/var/cache/nginx
    networks:
      - hjemmebehandling

   medarbejder-web:
    image: nginxinc/nginx-unprivileged:alpine3.17
    restart: always
    volumes:
      - ./medarbejder-web/init/docker-entrypoint.d:/docker-entrypoint.d
      - ./medarbejder-web/init/etc/nginx:/etc/nginx
      - ./medarbejder-web/init/var/run:/var/run
      - ./medarbejder-web/init/var/cache/nginx:/var/cache/nginx
    ports:
      - "3000:80"
    depends_on:
      - medarbejder-web-init
    networks:
      - hjemmebehandling

  # Mulige patienter kan ses i DIAS git. Patienter fremsøges via GET, f.eks. http://localhost:8081/Patient/2512489996
   rm-cpr-service:
    image: kvalitetsit/rm-cpr-service:0.2.0
    environment:
      - CPR_ENDPOINT=http://rm-cpr-service-mock:8080
      - DEBUG_LOGGING=true
    networks:
      - hjemmebehandling
    ports:
      - "8081:8080"

   rm-cpr-service-mock:
    image: kvalitetsit/rm-cpr-service-mock-backend:0.2.0
    environment:
      - DEBUG_LOGGING=true
    networks:
      - hjemmebehandling
     
   hapi-server:
    image: kvalitetsit/hjemmebehandling-hapi-fhir-server:dev
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/hapi
      - spring.datasource.username=hapi
      - spring.datasource.password=hapi
    depends_on:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hjemmebehandling
      
   hapi-server-initializer:
    image: alpine:3.11.5
    depends_on:
      hapi-server:
        condition: service_healthy
    working_dir: /hapi-server-initializer
    volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
    command: "./init-infektionsmedicinsk.sh"
    networks:
      - hjemmebehandling
      
   mariadb:
    image: mariadb:10.7
    environment:
      - MARIADB_USER=hapi
      - MARIADB_PASSWORD=hapi
      - MARIADB_ROOT_PASSWORD=hapi
      - MARIADB_DATABASE=hapi
    networks:
      - hjemmebehandling

