version: '2.1'

networks:
  rim:
    driver: bridge

services:
   samlsp:
     image: kvalitetsit/kitcaddy:1.2.22
     volumes:
       - ./medarbejder-web/certificates/medarbejder-web.cert:/sp/sp.cer
       - ./medarbejder-web/certificates/medarbejder-web.pem:/sp/sp.pem
       - ./medarbejder-web/config.json:/config/config.json
     command: -config /config/config.json
     ports:
      - "8080:8585"
     networks:
      - rim

   mongo:
     image: mongo:3.6
     networks:
      - rim

   medarbejder-bff:
     image: kvalitetsit/rim-medarbejder-bff:6f7a0b5292a1273e4d51afc7c03b2d82ff5bbe07
     networks:
      - rim

   medarbejder-web:
     image: kvalitetsit/rim-medarbejder-web:6ac4ca3df1c923dcc8b3441b7c64f1371fd00dc8
     networks:
      - rim

   rm-cpr-service:
     image: kvalitetsit/rm-cpr-service:0.2.0
     environment:
      - CPR_ENDPOINT=http://rm-cpr-service-mock:8080
      - DEBUG_LOGGING=true
     networks:
      - rim
     ports:
      - "8081:8080"

   rm-cpr-service-mock:
     image: kvalitetsit/rm-cpr-service-mock-backend:0.2.0
     environment:
      - DEBUG_LOGGING=true
     networks:
      - rim
     
   hapi-server:
     image: hapiproject/hapi:latest
     networks:
      - rim
     environment:
       - SPRING_CONFIG_LOCATION=file:///data/hapi/application.yaml
       - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
     volumes:
       - ./hapi-server/application.yaml:/data/hapi/application.yaml

   hapi-server-initializer:
     image: alpine:3.11.5
     depends_on:
       - hapi-server
     networks:
      - rim
     volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
     command: "/hapi-server-initializer/init.sh"
