version: '2.1'

networks:
  rim:
    driver: bridge

services:
   # login med {testbruger1,testbruger2}/Test1234 
   medarbejder-login-proxy:
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
      command: --config /oauth2-proxy.cfg
      ports:
       - 4180:4180
      volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
      networks:
       - rim

   medarbejder-bff:
      image: kvalitetsit/hjemmebehandling-medarbejder-bff:69ee3659feecae5617796c7fcb4b72f364068124
      environment:
       - cpr.url=http://rm-cpr-service:8080/Patient/
       - fhir.server.url=http://hapi-server:8080/fhir
       - user.context.handler=DIAS
      networks:
       - rim
       
   medarbejder-web:
     image: kvalitetsit/hjemmebehandling-medarbejder-web:447dce8778e0185ffce7eed06cf1d85e381263f1
     ports:
      - 3000:3000
     environment:
      - BFF_BASE_URL=http://medarbejder-bff:8080
     networks:
      - rim

   # Mulige patienter kan ses i DIAS git. Patienter fremsøges via GET, f.eks. http://localhost:8081/Patient/2512489996
   rm-cpr-service:
     image: kvalitetsit/rm-cpr-service:0.2.0
     environment:
      - CPR_ENDPOINT=http://rm-cpr-service-mock:8080
      - DEBUG_LOGGING=true
     networks:
      - rim
     ports:
      - "8081:8080"

   rm-cpr-service-mock:
     image: kvalitetsit/rm-cpr-service-mock-backend:0.2.0
     environment:
      - DEBUG_LOGGING=true
     networks:
      - rim

   mariadb:
     image: mariadb:10.7
     environment:
      - MARIADB_USER=hapi
      - MARIADB_PASSWORD=hapi
      - MARIADB_ROOT_PASSWORD=hapi
      - MARIADB_DATABASE=hapi
     networks:
      - rim  

   hapi-server:
     image: kvalitetsit/hjemmebehandling-hapi-fhir-server:103467cb33b8b22d899a8c051bf691283cb3faee 
     networks:
      - rim
     environment:
       - spring.datasource.url=jdbc:mysql://mariadb:3306/hapi
       - spring.datasource.username=hapi
       - spring.datasource.password=hapi
   hapi-server-initializer:
     image: alpine:3.11.5
     depends_on:
       - hapi-server
     networks:
      - rim
     working_dir: /hapi-server-initializer
     volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
     command: "./init-infektionsmedicinsk.sh"
