version: '2.1'

networks:
  rim:
    driver: bridge

services:
   medarbejder-bff:
     image: kvalitetsit/hjemmebehandling-medarbejder-bff:4706728c6a59acc64917fe86b7418ac798c3f770
     networks:
      - rim

   medarbejder-web:
     image: kvalitetsit/hjemmebehandling-medarbejder-web:61a87bc428be358f23a0ba4d257e8f8bcdf4c40f
     ports:
      - 3000:3000
     environment:
      - BFF_BASE_URL=http://medarbejder-bff:8080
     networks:
      - rim

   # Mulige patienter kan ses i DIAS git. Patienter fremsøges via GET, f.eks. http://localhost:8081/Patient/2512489996
   rm-cpr-service:
     image: kvalitetsit/rm-cpr-service:0.2.0
     environment:
      - CPR_ENDPOINT=http://rm-cpr-service-mock:8080
      - DEBUG_LOGGING=true
     networks:
      - rim
     ports:
      - "8081:8080"

   rm-cpr-service-mock:
     image: kvalitetsit/rm-cpr-service-mock-backend:0.2.0
     environment:
      - DEBUG_LOGGING=true
     networks:
      - rim
     
   hapi-server:
     image: hapiproject/hapi:latest
     networks:
      - rim
     environment:
       - SPRING_CONFIG_LOCATION=file:///data/hapi/application.yaml
       - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
     volumes:
       - ./hapi-server/application.yaml:/data/hapi/application.yaml

   hapi-server-initializer:
     image: alpine:3.11.5
     depends_on:
       - hapi-server
     networks:
      - rim
     volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
     command: "/hapi-server-initializer/init.sh"
