version: '2.1'

networks:
  rim:
    driver: bridge

services:
   samlsp:
     image: kvalitetsit/kitcaddy:1.2.22
     volumes:
       - ./medarbejder-web/certificates/medarbejder-web.cert:/sp/sp.cer
       - ./medarbejder-web/certificates/medarbejder-web.pem:/sp/sp.pem
       - ./medarbejder-web/config.json:/config/config.json
     command: -config /config/config.json
     ports:
      - "8080:8585"
     networks:
      - rim

   mongo:
     image: mongo:3.6
     networks:
      - rim

   medarbejder-bff:
     image: kvalitetsit/rim-medarbejder-bff:dev
     networks:
      - rim

   medarbejder-web:
     image: kvalitetsit/rim-medarbejder-web:dev
     networks:
      - rim

   hapi-server:
     image: hapiproject/hapi:latest
     networks:
      - rim

   hapi-server-initializer:
     image: alpine:3.11.5
     depends_on:
       - hapi-server
     networks:
      - rim
     volumes:
      - ./hapi-server-initializer:/hapi-server-initializer
     command: "/hapi-server-initializer/init.sh"
